name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    
    - name: Init build
      uses: rjstone/discord-webhook-notify@v1
      with:
          severity: info
          color: "#2188ff"
          details: Running build!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm test

    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: '${{ secrets.DOCKER_HUB_USERNAME }}'
        password: '${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}'

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: '${{ secrets.DOCKER_HUB_USERNAME }}/k8s-webhook-api:${{ github.sha }}'

    - name: Image digest
      run: 'echo ${{ steps.docker_build.outputs }}'

    - name: Replace image in config
      uses: datamonsters/replace-action@v2
      with:
        files: .devops/deployment.yaml
        replacements: '${IMAGE_TAG}=${{ github.sha }}'
  
    - name: Deploy to Kubernetes
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: v1.21.0 # specify kubectl binary version explicitly
        command: apply -f .devops/deployment.yaml
        
    - name: Build Success
      uses: rjstone/discord-webhook-notify@v1
      if: success()
      with:
          severity: info
          details: Build Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          
    - name: Build Failure
      uses: rjstone/discord-webhook-notify@v1
      if: failure()
      with:
          severity: error
          details: Build Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          
    - name: Build Cancelled
      uses: rjstone/discord-webhook-notify@v1
      if: cancelled()
      with:
          severity: warn
          details: Build Cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

